from matplotlib import pyplot as plt
import os,csv,numpy as np
os.chdir(r'J:\Python\Cfd_codes\Nptel_Code\STREAM_FUNCTION_EQUATION')
data=open('psi_GSIM.csv')
reader=csv.reader(data)
x=[];y=[];psi=[]
for row in reader:
    x.append(row[0])
    y.append(row[1])
    psi.append(row[2])
# psi = np.genfromtxt(data, delimiter=',')
psi=np.array(psi[1:])
X=np.array(x[1:])
Y=np.array(y[1:])
new_psi=psi.reshape(21,31)
print(new_psi)
z=np.load('psi.npy')
X_1=np.linspace(0,60,31)
Y_1=np.linspace(0,40,21)
x,y=np.meshgrid(X_1,Y_1)
# c = plt.contourf(x,y,new_psi,np.linspace(0,100,11))
c = plt.contourf(x,y,z,np.linspace(0,100,11))
b = plt.colorbar(c, orientation='vertical')
lx = plt.xlabel("x")
ly = plt.ylabel("y")
ax = plt.axis([0,60,0,40])
plt.show()
